### ISSUE TITLE
Provisioned Machines Not being assigned static ip

### ISSUE THREAD

**Issue by nashrafeeg** [NetApp/ez-rancher#117]
I have tried using both recommended bionic ovh and the latest ubuntu cloud server ovh without any luck. all three machines are provisioned without any IP address assigned

**Comment by hulquest** [comment]
Hello @nashrafeeg - I just made an issue template for the repository.  Will you update the description with this information so we can help you better?
`
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**ez-rancher log/output**:

**ez-rancher tfvars:**

**vCenter (please complete the following section):**
 - ESXi Version: [e.g. 6.7]
 - vCenter Version [e.g. 6.7]

**Docker (please complete the following section):**
- Version: 

**Additional context**
Add any other context about the problem here.

`
